name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          cache: true

      - name: Show Forge version
        run: |
          forge --version

      - name: Cache Soldeer dependencies
        uses: actions/cache@v4
        with:
          path: |
            dependencies
            remappings.txt
            soldeer.lock
          key: ${{ runner.os }}-soldeer-${{ hashFiles('soldeer.lock') }}
          restore-keys: |
            ${{ runner.os }}-soldeer-

      - name: Install dependencies (Soldeer)
        run: |
          forge soldeer install

      - name: Print remappings
        run: |
          forge remappings

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
